Add the possibility to call a callback when the buffer is saved
robotology/robometry pull request #159
Opened 2022-03-16 13:28 UTC by GiulioRomualdi

This PR implements the possibility to set a callback that is called every time the `saveToFile` is called. Thanks to this it will be possible to store other kinds of data, e.g. videos, txt files...

2022-03-29 17:15 UTC, GiulioRomualdi commented
cc @traversaro @S-Dafarra @Nicogene @AlexAntn

2022-03-31 15:51 UTC, Nicogene requested changes
Hi @GiulioRomualdi sorry for the delay!

It is not super clear to me a possible use case, could you add an example of it?

Maybe adding a test and could you please add it in the readme?

2022-05-04 09:18 UTC, Nicogene commented
Hi @GiulioRomualdi, what is the status of this PR?
We will do soon a release and then do some breaking changes that would trigger some conflicts with this PR

2022-05-05 22:29 UTC, GiulioRomualdi commented
> Hi @GiulioRomualdi, what is the status of this PR? We will do soon a release and then do some breaking changes that would trigger some conflicts with this PR


Hi @Nicogene, sorry for the delay. I updated the readme and the test I also apply what @S-Dafarra suggested. 

An use case for this PR is to save the videostream from the cameras. Thanks to this I can merge this: https://github.com/ami-iit/bipedal-locomotion-framework/pull/516

2022-05-06 07:12 UTC, S-Dafarra approved these changes

2022-05-06 08:39 UTC, Nicogene approved these changes
I will add a line in the changelog and I will release the v0.5.1 for including this patch before the renaming

2022-05-06 08:39 UTC, merged

2022-05-06 08:39 UTC, Nicogene commented
Merged, thanks!