Avoid using templates in BufferManager.
robotology/robometry pull request #175
Opened 2022-05-10 15:57 UTC by S-Dafarra

With this PR I completely removed the use of templates for ``BufferManager`` since the default template was in any case causing issues.

I have also fixed a small discrepancy in the definition of the dimensions of cell and struct arrays.

2022-05-10 16:59 UTC, S-Dafarra commented
cc @GiulioRomualdi @traversaro

2022-05-11 09:22 UTC, Nicogene commented on README.md
> +              data: {1×3 cell}
Why did you change it?

2022-05-11 09:24 UTC, Nicogene requested changes
Could you please add [this test](https://github.com/robotology/robometry/commit/fac3227c47aefc60e89442ee75f1365ead6d8057) for checking the issue this PR is addressing?

2022-05-11 09:29 UTC, S-Dafarra commented on README.md
> +              data: {1×3 cell}
See https://github.com/robotology/robometry/pull/175/commits/a6309eedc8419607dcb68f870bd87fd46eebe14a, I realized that for cell and struct arrays I was concatenating on the first dimension. This was causing differences with the ``dimensions`` vector.

You can actually see this mismatch in the previous version of the README: https://github.com/robotology/robometry/blob/14310e9a80c75eba987d647f02a91afe9f0c0512/README.md?plain=1#L367-L368

2022-05-11 12:36 UTC, Nicogene commented on README.md
> +              data: {1×3 cell}
Aaa I see

2022-05-11 12:36 UTC, Nicogene approved these changes
LGTM!

Is it ok for you @GiulioRomualdi @traversaro ?

2022-05-11 13:34 UTC, traversaro approved these changes

2022-05-11 14:43 UTC, merged