Add to TelemetryDeviceDumper streaming of rawValues from low level
robotology/robometry pull request #190
Opened 2024-09-18 15:46 UTC by MSECode

Add to the `telemetryDeviceDumper` a device based on the nwc `rawValuesPublisherClient` thus to save in the MATLAB file generated by this plugin the raw values (and whatever one desired for debugs based on the Interface `iCub::debugLibrary::IRawValuesPublisher`) coming from the boards at the fw level.

**Side Note:** I'll open this PR since I've tested the update done on my bench setup. However, the work, even though at a good point, cannot be considered fully completed. The PR will be kept in draft for now and used for discussion on the updates done and to revise them together

cc: @valegagge @Nicogene @traversaro

2024-10-03 08:23 UTC, S-Dafarra commented
To be honest, I believe that the dependency on iCub is not the best here, as it would complexify its usage with other robots. An alternative could be to instead create a similar device in icub-main instead

2024-10-04 21:30 UTC, valegagge commented
> To be honest, I believe that the dependency on iCub is not the best here, as it would complexify its usage with other robots. An alternative could be to instead create a similar device in icub-main instead

Hi @S-Dafarra ,
I don't understand your suggestion, sorry! :( The new device belongs to icub-main, so here we add the dependence from it.

2024-10-04 21:36 UTC, valegagge commented
Hi @MSECode ,
for me is ok.
I found a small bug related to the use of `logControlBoardQuantities` with `false `value, but it seems not dependent on your changes.
I fixed here. Asap I'll put the code (I need the permission.)

2024-10-07 07:44 UTC, S-Dafarra commented
> The new device belongs to icub-main, so here we add the dependence from it.

That's the problem, the new dependency from ``icub-main``, while it should be the other way around. In other words, it should be ``icub-main`` to depend from ``robometry``, and this can be done by moving or copying the ``TelemetryDeviceDumper `` device into ``icub-main``.

2024-10-07 08:36 UTC, Nicogene commented
> > The new device belongs to icub-main, so here we add the dependence from it.
> 
> That's the problem, the new dependency from `icub-main`, while it should be the other way around. In other words, it should be `icub-main` to depend from `robometry`, and this can be done by moving or copying the `TelemetryDeviceDumper ` device into `icub-main`.

Note that the dependency from `icub-main` would be added only if `telemetryDeviceDumper` is compiled, and it is disabled by default.

In any case, I am more comfortable to move it eventually in `icub-main`, rather than have yet another logger device around

2024-10-07 08:39 UTC, S-Dafarra commented
> In any case, I am more comfortable to move it eventually in `icub-main`, rather than have yet another logger device around

I agree! Your call anyway 👍

2024-10-07 11:54 UTC, Nicogene commented
Another possibility is to add a `find_package(iCub QUIET)` and then use a `ifdef` in the `telemetryDeviceDumper` code, this would keep it compilable also without `icub-main`

2024-10-08 10:01 UTC, valegagge commented
Hi @Nicogene and @S-Dafarra ,
I'm sorry for not getting back to you sooner. 

@S-Dafarra : when we decided to add this functionality we knew we were adding a dependency to `icub-main`, but agreed with @Nicogene we decided to go ahead.
As you point out maybe it is too strong to make this dependency permanent. 
If I can post my few cents, I think we can keep the dependency from `Telemetrydumper` optional as @Nicogene suggested in the previous comment.

What do you think?

2024-10-08 12:31 UTC, valegagge commented
Hi @MSECode ,
this is the [commit](https://github.com/robotology/robometry/pull/190/commits/ed30a2cc57762bc796149b3a11126a8669755c8f) of the fis I mentioned [here](https://github.com/robotology/robometry/pull/190#issuecomment-2394702705).

2024-10-09 13:26 UTC, MSECode commented
> Hi @MSECode , this is the [commit](https://github.com/robotology/robometry/pull/190/commits/ed30a2cc57762bc796149b3a11126a8669755c8f) of the fis I mentioned [here](https://github.com/robotology/robometry/pull/190#issuecomment-2394702705).

Yes, I saw it and squashed to 1 single commit for the PR. 
Let's now decide how to managed the CMakeLists.txt file for what said in the thread and eventually add the fixes and proceed with the PR. Is it OK?

2024-10-10 09:40 UTC, valegagge commented
As discussed with @MSECode and @Nicogene , we'll organize a meeting with all the involved people to define if moving the device to `icub-main` or not or, in any case, point out the best solution.

2024-10-10 21:45 UTC, S-Dafarra commented
Let me add that the device is already dependent on ``yarp``, as it should be, so in any case, we already need for ``yarp`` to be compiled before. In general, I keep not liking to have ``icub-main`` as a dependency here because it hinders any usage of `robometry` within ``icub-main``. Still, I don't want to make a big fuzz out of this, so feel free to proceed with the solution you feel more suitable.

2024-10-16 13:37 UTC, pattacini commented
I didn't follow this discussion in the first place, but probably a better place for the I/F's would have been YARP itself. The implementation of the devices can stay in icub-main, but we usually put the I/F's in YARP right to address this kind of situation.

At any rate, we can discuss this topic with the ad-hoc meeting you scheduled.

2024-10-16 14:40 UTC, traversaro commented
> I didn't follow this discussion in the first place, but probably a better place for the I/F's would have been YARP itself. The implementation of the devices can stay in icub-main, but we usually put the I/F's in YARP right to address this kind of situation.
> 
> At any rate, we can discuss this topic with the ad-hoc meeting you scheduled.

We can discuss in person, but the idea was to have the interface somewhere maintained by iCub Tech to be able to quicky iterate if necessary.

2024-10-31 17:17 UTC, Nicogene commented on src/telemetryDeviceDumper/CMakeLists.txt
> +  find_package(iCubDev REQUIRED)
Have you bumped the patch version of icub-main? I would put here the required version that includes the new interface

2024-10-31 17:20 UTC, Nicogene requested changes
Some small changes requested

2024-10-31 17:20 UTC, Nicogene commented on src/telemetryDeviceDumper/TelemetryDeviceDumper.h
> + * | `logIRawValuesPublisher` | bool |   -   | false    | No | Enable the log of raw values |
I would add a link to the interface stored in icub-main

2024-10-31 17:20 UTC, Nicogene commented on src/telemetryDeviceDumper/TelemetryDeviceDumper.h
> + * | `raw_data_values`          | [`iCub::debugLibrary::IRawValuesPublisher::getRawDataMap`]
Same as above

2024-10-31 17:22 UTC, MSECode commented on src/telemetryDeviceDumper/CMakeLists.txt
> +  find_package(iCubDev REQUIRED)
Yes, actually as suggested by @pattacini we bumped the minor version.

2024-10-31 17:40 UTC, Nicogene commented on src/telemetryDeviceDumper/CMakeLists.txt
> +  find_package(iCubDev REQUIRED)
Great! It should be then `find_package(iCubDev 2.7.0 REQUIRED)`, and I would also add it in the readme documentation of the device that that version of `icub-main` is required

2024-11-01 17:45 UTC, MSECode commented on src/telemetryDeviceDumper/TelemetryDeviceDumper.h
> + * | `logIRawValuesPublisher` | bool |   -   | false    | No | Enable the log of raw values |
done

2024-11-01 17:45 UTC, MSECode commented on src/telemetryDeviceDumper/TelemetryDeviceDumper.h
> + * | `raw_data_values`          | [`iCub::debugLibrary::IRawValuesPublisher::getRawDataMap`]
done

2024-11-01 17:45 UTC, MSECode commented on src/telemetryDeviceDumper/CMakeLists.txt
> +  find_package(iCubDev REQUIRED)
done

2024-11-07 11:31 UTC, Nicogene approved these changes

2024-11-07 11:34 UTC, merged